spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vstdb?useSSL=false&serverTimezone=UTC
    username: root
    password: csp@success
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # change to create / create-drop only if needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
