apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: virtual-stock-trader

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

# Image tag overrides for CI/CD
images:
  - name: cavinsam/virtual-stock-trading-app-backend
    newTag: latest
  - name: cavinsam/virtual-stock-trading-app-frontend
    newTag: latest
